#!/usr/bin/env bash

pd() {
    { case "$1" in
        +[0-9]) pushd "$1" || return 1 ;;
        -[0-9]) popd +"${1//[!0-9]/}" || return 1 ;;
        -) popd || return 1 ;;
        -c) dirs -c ;;
        *) pushd "$@" || return 1 ;;
    esac
    } > /dev/null
    dirs -v
}

killbg() {
    local array confirm pid

    readarray -t array < <(jobs -p)
    [[ -z "${array[*]}" ]] && { printf "killbg: no such job\n" >&2; return 1; }
    [[ -z "$1" ]] && {
        jobs -l
        read -erp "Kill: ${array[*]}? [y/n]: " confirm
        [[ ! "${confirm,,}" =~ ^y(es)?$ ]] && return 0; }
    for pid in "${array[@]}"; do kill "${1:--15}" "$pid"; done
    sleep .1; jobs
}

clean_history() {
    local hist hist_tmp
    hist="${HOME}/.bash_history"

    if [[ -f "$hist" ]]; then
        hist_tmp="$(tac "$hist" | awk '{$1=$1}1 && !x[$0]++' | tac)"
        echo "$hist_tmp" > "$hist"
    fi
}

extract() {
    case "$1" in
        *.tar.bz2) tar xjf "$1" ;;
        *.tar.gz) tar xzf "$1" ;;
        *.bz2) bunzip2 "$1" ;;
        *.rar) rar x "$1" ;;
        *.gz) gunzip "$1" ;;
        *.tar) tar xf "$1" ;;
        *.tbz2) tar xjf "$1" ;;
        *.tgz) tar xzf "$1" ;;
        *.zip) unzip "$1" ;;
        *.Z) uncompress "$1" ;;
        *.7z) 7z x "$1" ;;
        *) printf "%s cannot be extracted" "$1" >&2; return 1 ;;
    esac
}

compress() {
    if [[ -z "$1" ]]; then
        printf "compress: must provide file/directory path\n" 1>&2; return 1
    elif [[ -d "$1" ]]; then
        tar -czf "${1%/}.tar.gz" "$1";
    elif [[ -f "$1" ]]; then
        tar -czf "${1}.gz" "$1";
    else
        printf "compress: %s: invalid path\n" "$1" 1>&2; return 1
    fi
}

checkmounts() {
    local mount

    while read -r mount; do
        if ! findmnt "$mount" &> /dev/null; then
            printf "\033[31m%s is declared in fstab but not mounted\n\033[0m" "$mount" >&2
        else
            printf "%s is mounted properly\n" "$mount"
        fi
    done < <(awk '!/^#/ && $2~/^[/]/ {print $2}' /etc/fstab)
}

checkfs() {
    local mount

    timeout 2 df &> /dev/null || { printf "Hung mount detected.\n" >&2; return 1; }
    while read -r mount; do
        findmnt "$mount" &> /dev/null || {
        printf "%s is declared in fstab but not mounted\n" "$mount" >&2; }
    done < <(awk '!/^#/ && $2~/^[/]/ {print $2}' /etc/fstab)
    printf "Full File Systems:\n%s\n" "$(df -h | grep "100%" || printf "None\n")"
    printf "Full Inodes:\n%s\n" "$(df -i | grep "100%" || printf "None\n")"
}

thetime() {
    local zulu central

    zulu="$(date -u +"%a %b %-d, %Y - %R:%S")"
    central="$(TZ="America/Chicago" date +"%a %b %-d, %Y - %R:%S")"

    printf "CDT: %s\nUTC: %s\n" "$central" "$zulu"
}
