#!/usr/bin/env bash

reset='\033[0m'
bold='\033[1m'
dim='\033[2m'
italic='\033[3m'
under='\033[4m'
blink='\033[5m'
reverse='\033[7m'
invisible='\033[8m'
black='\x1b[30m'
red='\033[38;5;160m'
green='\033[38;5;119m'
yellow='\033[38;5;226m'
blue='\033[38;5;33m'
magenta='\033[38;5;207m'
cyan='\033[38;5;51m'
grey='\033[38;5;251m'
purple='\033[38;5;129m'
white='\x1b[37m'
bg_black='\x1b[40m'
bg_red='\x1b[41m'
bg_green='\x1b[42m'
bg_yellow='\x1b[43m'
bg_blue='\x1b[44m'
bg_magenta='\x1b[45m'
bg_cyan='\x1b[46m'
bg_white='\x1b[47m'

PRINT() {
    case $1 in
        bold)           color=$bold         ;;
        dim)            color=$dim          ;;
        italic)         color=$italic       ;;
        under)          color=$under        ;;
        blink)          color=$blink        ;;
        reverse)        color=$reverse      ;;
        invisible)      color=$invisible    ;;
        red)            color=$red          ;;
        green)          color=$green        ;;
        yellow)         color=$yellow       ;;
        blue)           color=$blue         ;;
        magenta)        color=$magenta      ;;
        cyan)           color=$cyan         ;;
        grey)           color=$grey         ;;
        purple)         color=$purple       ;;
        white)          color=$white        ;;
        bg_black)       color=$bg_black     ;;
        bg_red)         color=$bg_red       ;;
        bg_green)       color=$bg_green     ;;
        bg_yellow)      color=$bg_yellow    ;;
        bg_blue)        color=$bg_blue      ;;
        bg_magenta)     color=$bg_magenta   ;;
        bg_cyan)        color=$bg_cyan      ;;
        bg_white)       color=$bg_white     ;;
    esac
        printf "${color}%s${reset}\n" "$2"
}

export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;33m'
export LESS_TERMCAP_so=$'\e[01;44;37m'
export LESS_TERMCAP_us=$'\e[01;37m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export GROFF_NO_SGR=1
