#!/usr/bin/env bash

pd() {
{    case "${1}" in
        -[0-9]) popd +"${1//[!0-9]/}" || return ;;
        +[0-9]) pushd "$1" || return ;;
        -c) dirs -c ;;
        -) popd || return ;;
        *) pushd "$@" || return ;;
    esac
} > /dev/null
dirs -v
}

extract() {
    case "$1" in
        *.tar.bz2)   tar xjf "$1"      ;;
        *.tar.gz)    tar xzf "$1"      ;;
        *.bz2)       bunzip2 "$1"      ;;
        *.rar)       rar x "$1"        ;;
        *.gz)        gunzip "$1"       ;;
        *.tar)       tar xf "$1"       ;;
        *.tbz2)      tar xjf "$1"      ;;
        *.tgz)       tar xzf "$1"      ;;
        *.zip)       unzip "$1"        ;;
        *.Z)         uncompress "$1"   ;;
        *.7z)        7z x "$1"         ;;
        *)           printf "%s cannot be extracted" "$1" ;;
    esac
}

checkmounts() {
mountpoints=($(awk '$1 !~ /^#/ && $2 ~ /^[/]/ {print $2}' /etc/fstab))
for mount in "${mountpoints[@]}"; do
   if ! findmnt "$mount" &> /dev/null; then
      printf "%s is declared in fstab but not mounted" "$mount"
   else
      printf "$mount is mounted properly" "$mount"
   fi
done
}
